### ISSUE TITLE
Unable to install on Windows 10  Log Pasted below

### ISSUE THREAD

**Issue by HiramanRathod** [appitierre/aptr-uikit#116]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.3
3 info using node@v6.6.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle aptr-uikit-demo@1.0.3~predev: aptr-uikit-demo@1.0.3
6 silly lifecycle aptr-uikit-demo@1.0.3~predev: no script for predev, continuing
7 info lifecycle aptr-uikit-demo@1.0.3~dev: aptr-uikit-demo@1.0.3
8 verbose lifecycle aptr-uikit-demo@1.0.3~dev: unsafe-perm in lifecycle true
9 verbose lifecycle aptr-uikit-demo@1.0.3~dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\xx.xxx\Desktop\aptr-uikit-master\node_modules\.bin;C:\Program Files\nodejs;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Skype\Phone\;C:\Users\xx.xxx\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\
10 verbose lifecycle aptr-uikit-demo@1.0.3~dev: CWD: C:\Users\xx.xxx\Desktop\aptr-uikit-master
11 silly lifecycle aptr-uikit-demo@1.0.3~dev: Args: [ '/d /s /c', 'gulp' ]
12 silly lifecycle aptr-uikit-demo@1.0.3~dev: Returned: code: 1  signal: null
13 info lifecycle aptr-uikit-demo@1.0.3~dev: Failed to exec dev script
14 verbose stack Error: aptr-uikit-demo@1.0.3 dev: `gulp`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid aptr-uikit-demo@1.0.3
16 verbose cwd C:\Users\xx.xxx\Desktop\aptr-uikit-master
17 error Windows_NT 10.0.10240
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.6.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error aptr-uikit-demo@1.0.3 dev: `gulp`
22 error Exit status 1
23 error Failed at the aptr-uikit-demo@1.0.3 dev script 'gulp'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the aptr-uikit-demo package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs aptr-uikit-demo
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls aptr-uikit-demo
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by wesatkinson** [comment]
The APTR UI kit is not supported on Windows.
