### ISSUE TITLE
npm WARN install Refusing to install aptr-uikit as a dependency of itself

### ISSUE THREAD

**Issue by aniketdharia** [appitierre/aptr-uikit#117]
sudo npm install aptr-uikit --save
npm WARN package.json aptr-uikit@1.0.3 No repository field.
npm WARN package.json aptr-uikit@1.0.3 No license field.
npm WARN install Refusing to install aptr-uikit as a dependency of itself

Change the name in the package.json file to resolve this issue

**Comment by aniketdharia** [comment]
@salali in general not able to install the UI kit on my Mac. any reasons for it?

**Comment by wesatkinson** [comment]
Hi, apologies if it wasn't clear from Sal's label. We don't support or troubleshoot installation issues on this project, especially as we use this every day without issue.  We recommend you explore or raise any generic node based setup errors on StackOverflow.

**Comment by aniketdharia** [comment]
👍

**Comment by aniketdharia** [comment]
@wesatkinson got it to work finally. Had sometime today. Its a cool collection! Great Job by team Aptr! Cheers!
