### ISSUE TITLE
appitierre and connecting it with adapt

### ISSUE THREAD

**Issue by mes333** [appitierre/aptr-uikit#16]
Hi Not sure if I am doing something wrong... but I wanted to try out the aptr-uikit on my version of adapt. Unforunately it isn't working for me so far? I am just wondering if you have a tutorial or if their is a specific adapt version I should be using to get this working. I would like to test out the program with courses I have already built.

**Comment by darylhedley** [comment]
Hi @mes333 this is used for apps that support [React.js](https://facebook.github.io/react/) as all our components are built using the framework. This isn't so much a library for Adapt but more a kit to help build UI, Interactions and apps faster. We use it internally inside our Adapt, Evolve and Bloom apps. If you're looking for a program to help build Adapt courses there's the [OS version here](https://github.com/adaptlearning/adapt_authoring) or you can try [Evolve](http://evolveauthoring.com/)

Hope this helps explain the use of this library
