### ISSUE TITLE
A dropdown component for showing a list of actions/buttons

### ISSUE THREAD

**Issue by akramali86** [appitierre/aptr-uikit#19]
I know we got the dropdown component which is useful for dropping down any react element, but think it would be also great to have one that you just pass a list of actions, the actions are just props that get passed to the FlatButtons that are rendered in the list

**Comment by darylhedley** [comment]
@brandonk1234 @akramali86 there is a select option dropdown which passes back an onChange

**Comment by akramali86** [comment]
@darylhedley yeah i agree it should do the job, i wasn't aware of we had something like this. closing
