### ISSUE TITLE
ListItem

### ISSUE THREAD

**Issue by darylhedley** [appitierre/aptr-uikit#22]
Needs to pass in all props of the buttons into the flat buttons - for instance toolTips

can we do something like:

<FlatButton
    key={key}
    {...button}
/>

so the spread operator takes all props onto the flat button
in renderButtons

**Comment by darylhedley** [comment]
Should these also be li elements

**Comment by darylhedley** [comment]
oh and if you have no icon defined it still keeps the spacing on the icon

**Comment by brandonk1234** [comment]
There already li elements already aren't they? @darylhedley

**Comment by darylhedley** [comment]
yes - sorry I take it back @brandonk1234 - was from before
